add fans docker image + github actions workflow

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -3,6 +3,7 @@
 # during build time, don't ask for user input (has to be included in every stage
 # to take effect
 ARG DEBIAN_FRONTEND=noninteractive
+ARG WORKSPACE=/workspace
 
 ################################################################################
 
@@ -49,6 +50,70 @@ RUN apt-get update -qq && apt-get install -y --no-install-recommends \
     && apt-get clean \
     && apt-get autoremove --purge -y \
     && rm -rf /var/lib/apt/lists/*
+
+# Create a non-root user
+ENV USER=develop
+ENV UID=1000
+ENV GID=100
+ENV HOME=/home/${USER}
+RUN adduser --disabled-password \
+    --gecos "Non-root user" \
+    --uid ${UID} \
+    --gid ${GID} \
+    --home ${HOME} \
+    ${USER} \
+    #
+    && echo ${USER} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USER} \
+    && chmod 0440 /etc/sudoers.d/${USER}
+
+# entrypoint script changes uid and gid to match given host uid and gid
+COPY --chmod=755 docker/Dockerfile_user_env_entrypoint.sh /entrypoint.sh
+ENTRYPOINT ["/entrypoint.sh"]
+
+CMD ["bash"]
+
+################################################################################
+# These stages are for the standalone FANS container
+# The docker build context must contain the built FANS binaries including the
+# CMake build files in the directory ./build !
+################################################################################
+
+# we use the prebuilt fans-ci image here to save time. Needs to be pushed to
+# Dockerhub first!
+FROM unistuttgartdae/fans-ci AS fans_built
+ARG DEBIAN_FRONTEND
+ARG WORKSPACE
+
+# copy whole repository into the image
+COPY ./build ${WORKSPACE}
+
+WORKDIR ${WORKSPACE}
+
+RUN cpack -G "DEB"
+
+# only keep the runtime package and move it to the root of WORKSPACE
+RUN find . -type f ! -name 'fans_*.deb' -delete && \
+    find . -type f -name 'fans_*.deb' -exec mv {} . \; && \
+    find . ! -name 'fans_*.deb' -delete
+
+################################################################################
+
+FROM fans_base AS fans
+ARG DEBIAN_FRONTEND
+ARG WORKSPACE
+
+COPY --from=fans_built ${WORKSPACE} ${WORKSPACE}
+RUN [ $(ls ${WORKSPACE}/*.deb | wc -l) -eq 1 ] || (echo "Error: Expected exactly one .deb file" && exit 1)
+
+RUN apt-get update -qq && apt-get install -y --no-install-recommends \
+    ${WORKSPACE}/*.deb \
+    sudo \
+    gosu \
+    && apt-get clean \
+    && apt-get autoremove --purge -y \
+    && rm -rf /var/lib/apt/lists/*
+
+RUN rm -rf ${WORKSPACE}
 
 # Create a non-root user
 ENV USER=develop
